### ISSUE TITLE
Error when using two tooltips with same ID on same page

### ISSUE THREAD

**Issue by osrsbox** [osrsbox/osrsbox-tooltips#13]
If you have multiple tooltips on the same page, if any of them have the same IDs, only the first one will work. Tested with the following code. 

```
<span class="osrstooltip" id="11802" data-type="half" title="Please wait...">Armadyl Godsword</span>
<span class="osrstooltip" id="11802" data-type="bonuses" title="Please wait ...">Armadyl Godsword</span>
```

**Comment by osrsbox** [comment]
I came up with an idea how to fix this issue. The tooltip bug is caused by the issue that two HTML elements have the same `id` on the same page - which goes against the usage of the `id` property. 

Solution: Add a random string to each tooltip `id` after the requested item ID. For example: `id="11802-7Gb8dS"`. Then you could easily strip the random number suffix. Pseduocode:

```
item_id = id.split("-")[0]
````

This could be a optional addition, and the tooltip code could be written to determine if a dash (`-`) is found in the `id` element. One drawback... the random string insertion into the `id` would be a manual entry that a user/web developer would have to add.

**Comment by while-loop** [comment]
I took a swing at this issue (#16). The proposed method allows the change to be backwards compatible so existing usage doesn't need to add a uuid to each element.
