### ISSUE TITLE
Improve the quickstart page to provide integrity check hashes & library versioning

### ISSUE THREAD

**Issue by hex-agon** [osrsbox/osrsbox-tooltips#5]
Currently the https://www.osrsbox.com/projects/osrsbox-tooltips/ page provides snippets for scripts & css without integrity check hashes. Even though people can calculate the hashes themselves it would be nice if the guide page actually suggested using them. In order to include the SRI hashes it would also be required to version the resources otherwise changes in them would cause them to fail to load on the users end.

Further reading on the subject:
https://www.troyhunt.com/the-javascript-supply-chain-paradox-sri-csp-and-trust-in-third-party-libraries/
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by osrsbox** [comment]
Accidentally used to wrong issue reference number and closed this issue. Re-opening it - as I too think it is a good idea. Also, sorry about the delay in seeing this issue. I have put it on my to-do list.
