### ISSUE TITLE
data['members_only'] always returns false

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-tooltips#7]
Hey! Amazing project, I'm going to put it to good use.

One thing i've noticed, your plugin files reference `data['members_only']`, which doesn't exist, therefor all items are showing as false for members only :)

Your JSON returns `data['members']`.

**Comment by osrsbox** [comment]
Many thanks for the issue report. Should be fixed now - tested and was working fine on my local sample page using an Armadyl godsword (ID: 11802).
